[package]
name = "divera"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7", features = ["rustls-tls", "json", "blocking"],  default-features = false}
serde = { version = "1.0.214", features = ["derive"] }
log = "0.4.22"
thiserror = "2.0.0"
serde_json = "1.0.132"
